CREATE TABLE `UserMoodsModel`(
	`CreatedBy` VARCHAR(32),
	`CreatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	`LastUpdatedBy` VARCHAR(32),
	`LastUpdatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
	`mood` VARCHAR(40) NOT NULL,
	`SoftDeleteFlag` BOOLEAN,
	`uuid` VARCHAR(40) NOT NULL,
	PRIMARY KEY(`uuid`)
);
ALTER TABLE `UserMoodsModel`
	ADD CONSTRAINT `767c006fd45f75a1f5cfbf400a05ba` UNIQUE KEY(`mood`),
	ADD CONSTRAINT `631d860cc2e050aa4227759b6e6c84` UNIQUE KEY(`uuid`);
